(cl:defpackage ramp_msgs-srv
  (:use )
  (:export
   "EVALUATIONSRV"
   "<EVALUATIONSRV-REQUEST>"
   "EVALUATIONSRV-REQUEST"
   "<EVALUATIONSRV-RESPONSE>"
   "EVALUATIONSRV-RESPONSE"
   "MODIFICATIONREQUEST"
   "<MODIFICATIONREQUEST-REQUEST>"
   "MODIFICATIONREQUEST-REQUEST"
   "<MODIFICATIONREQUEST-RESPONSE>"
   "MODIFICATIONREQUEST-RESPONSE"
   "NAVMODIFICATIONREQUEST"
   "<NAVMODIFICATIONREQUEST-REQUEST>"
   "NAVMODIFICATIONREQUEST-REQUEST"
   "<NAVMODIFICATIONREQUEST-RESPONSE>"
   "NAVMODIFICATIONREQUEST-RESPONSE"
   "TRAJECTORYSRV"
   "<TRAJECTORYSRV-REQUEST>"
   "TRAJECTORYSRV-REQUEST"
   "<TRAJECTORYSRV-RESPONSE>"
   "TRAJECTORYSRV-RESPONSE"
  ))

