# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ramp_msgs/CircleGroup.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import ramp_msgs.msg

class CircleGroup(genpy.Message):
  _md5sum = "9a0c5849cc79a80224d0f73cc03d9dab"
  _type = "ramp_msgs/CircleGroup"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """ramp_msgs/Circle fitCir
ramp_msgs/Circle[] packedCirs

================================================================================
MSG: ramp_msgs/Circle
geometry_msgs/Vector3 center
float64 radius

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['fitCir','packedCirs']
  _slot_types = ['ramp_msgs/Circle','ramp_msgs/Circle[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       fitCir,packedCirs

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CircleGroup, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.fitCir is None:
        self.fitCir = ramp_msgs.msg.Circle()
      if self.packedCirs is None:
        self.packedCirs = []
    else:
      self.fitCir = ramp_msgs.msg.Circle()
      self.packedCirs = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4d().pack(_x.fitCir.center.x, _x.fitCir.center.y, _x.fitCir.center.z, _x.fitCir.radius))
      length = len(self.packedCirs)
      buff.write(_struct_I.pack(length))
      for val1 in self.packedCirs:
        _v1 = val1.center
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(_get_struct_d().pack(val1.radius))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.fitCir is None:
        self.fitCir = ramp_msgs.msg.Circle()
      if self.packedCirs is None:
        self.packedCirs = None
      end = 0
      _x = self
      start = end
      end += 32
      (_x.fitCir.center.x, _x.fitCir.center.y, _x.fitCir.center.z, _x.fitCir.radius,) = _get_struct_4d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.packedCirs = []
      for i in range(0, length):
        val1 = ramp_msgs.msg.Circle()
        _v2 = val1.center
        _x = _v2
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 8
        (val1.radius,) = _get_struct_d().unpack(str[start:end])
        self.packedCirs.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4d().pack(_x.fitCir.center.x, _x.fitCir.center.y, _x.fitCir.center.z, _x.fitCir.radius))
      length = len(self.packedCirs)
      buff.write(_struct_I.pack(length))
      for val1 in self.packedCirs:
        _v3 = val1.center
        _x = _v3
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        buff.write(_get_struct_d().pack(val1.radius))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.fitCir is None:
        self.fitCir = ramp_msgs.msg.Circle()
      if self.packedCirs is None:
        self.packedCirs = None
      end = 0
      _x = self
      start = end
      end += 32
      (_x.fitCir.center.x, _x.fitCir.center.y, _x.fitCir.center.z, _x.fitCir.radius,) = _get_struct_4d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.packedCirs = []
      for i in range(0, length):
        val1 = ramp_msgs.msg.Circle()
        _v4 = val1.center
        _x = _v4
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 8
        (val1.radius,) = _get_struct_d().unpack(str[start:end])
        self.packedCirs.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
