# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ramp_msgs/EvaluationResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class EvaluationResponse(genpy.Message):
  _md5sum = "f964edf11b680c3f41b2a601ea124cac"
  _type = "ramp_msgs/EvaluationResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 fitness
bool feasible
duration t_firstCollision
"""
  __slots__ = ['fitness','feasible','t_firstCollision']
  _slot_types = ['float64','bool','duration']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       fitness,feasible,t_firstCollision

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EvaluationResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.fitness is None:
        self.fitness = 0.
      if self.feasible is None:
        self.feasible = False
      if self.t_firstCollision is None:
        self.t_firstCollision = genpy.Duration()
    else:
      self.fitness = 0.
      self.feasible = False
      self.t_firstCollision = genpy.Duration()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_dB2i().pack(_x.fitness, _x.feasible, _x.t_firstCollision.secs, _x.t_firstCollision.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.t_firstCollision is None:
        self.t_firstCollision = genpy.Duration()
      end = 0
      _x = self
      start = end
      end += 17
      (_x.fitness, _x.feasible, _x.t_firstCollision.secs, _x.t_firstCollision.nsecs,) = _get_struct_dB2i().unpack(str[start:end])
      self.feasible = bool(self.feasible)
      self.t_firstCollision.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_dB2i().pack(_x.fitness, _x.feasible, _x.t_firstCollision.secs, _x.t_firstCollision.nsecs))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.t_firstCollision is None:
        self.t_firstCollision = genpy.Duration()
      end = 0
      _x = self
      start = end
      end += 17
      (_x.fitness, _x.feasible, _x.t_firstCollision.secs, _x.t_firstCollision.nsecs,) = _get_struct_dB2i().unpack(str[start:end])
      self.feasible = bool(self.feasible)
      self.t_firstCollision.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_dB2i = None
def _get_struct_dB2i():
    global _struct_dB2i
    if _struct_dB2i is None:
        _struct_dB2i = struct.Struct("<dB2i")
    return _struct_dB2i
