// Generated by gencpp from file ramp_msgs/CircleGroup.msg
// DO NOT EDIT!


#ifndef RAMP_MSGS_MESSAGE_CIRCLEGROUP_H
#define RAMP_MSGS_MESSAGE_CIRCLEGROUP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ramp_msgs/Circle.h>
#include <ramp_msgs/Circle.h>

namespace ramp_msgs
{
template <class ContainerAllocator>
struct CircleGroup_
{
  typedef CircleGroup_<ContainerAllocator> Type;

  CircleGroup_()
    : fitCir()
    , packedCirs()  {
    }
  CircleGroup_(const ContainerAllocator& _alloc)
    : fitCir(_alloc)
    , packedCirs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::ramp_msgs::Circle_<ContainerAllocator>  _fitCir_type;
  _fitCir_type fitCir;

   typedef std::vector< ::ramp_msgs::Circle_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ramp_msgs::Circle_<ContainerAllocator> >::other >  _packedCirs_type;
  _packedCirs_type packedCirs;





  typedef boost::shared_ptr< ::ramp_msgs::CircleGroup_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ramp_msgs::CircleGroup_<ContainerAllocator> const> ConstPtr;

}; // struct CircleGroup_

typedef ::ramp_msgs::CircleGroup_<std::allocator<void> > CircleGroup;

typedef boost::shared_ptr< ::ramp_msgs::CircleGroup > CircleGroupPtr;
typedef boost::shared_ptr< ::ramp_msgs::CircleGroup const> CircleGroupConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ramp_msgs::CircleGroup_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ramp_msgs::CircleGroup_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ramp_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ramp_msgs': ['/home/mason/Documents/evol_planner/src/packages/ramp_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ramp_msgs::CircleGroup_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ramp_msgs::CircleGroup_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ramp_msgs::CircleGroup_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ramp_msgs::CircleGroup_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ramp_msgs::CircleGroup_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ramp_msgs::CircleGroup_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ramp_msgs::CircleGroup_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9a0c5849cc79a80224d0f73cc03d9dab";
  }

  static const char* value(const ::ramp_msgs::CircleGroup_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9a0c5849cc79a802ULL;
  static const uint64_t static_value2 = 0x24d0f73cc03d9dabULL;
};

template<class ContainerAllocator>
struct DataType< ::ramp_msgs::CircleGroup_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ramp_msgs/CircleGroup";
  }

  static const char* value(const ::ramp_msgs::CircleGroup_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ramp_msgs::CircleGroup_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ramp_msgs/Circle fitCir\n\
ramp_msgs/Circle[] packedCirs\n\
\n\
================================================================================\n\
MSG: ramp_msgs/Circle\n\
geometry_msgs/Vector3 center\n\
float64 radius\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::ramp_msgs::CircleGroup_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ramp_msgs::CircleGroup_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fitCir);
      stream.next(m.packedCirs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CircleGroup_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ramp_msgs::CircleGroup_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ramp_msgs::CircleGroup_<ContainerAllocator>& v)
  {
    s << indent << "fitCir: ";
    s << std::endl;
    Printer< ::ramp_msgs::Circle_<ContainerAllocator> >::stream(s, indent + "  ", v.fitCir);
    s << indent << "packedCirs[]" << std::endl;
    for (size_t i = 0; i < v.packedCirs.size(); ++i)
    {
      s << indent << "  packedCirs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ramp_msgs::Circle_<ContainerAllocator> >::stream(s, indent + "    ", v.packedCirs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAMP_MSGS_MESSAGE_CIRCLEGROUP_H
