// Generated by gencpp from file ramp_msgs/EvaluationSrv.msg
// DO NOT EDIT!


#ifndef RAMP_MSGS_MESSAGE_EVALUATIONSRV_H
#define RAMP_MSGS_MESSAGE_EVALUATIONSRV_H

#include <ros/service_traits.h>


#include <ramp_msgs/EvaluationSrvRequest.h>
#include <ramp_msgs/EvaluationSrvResponse.h>


namespace ramp_msgs
{

struct EvaluationSrv
{

typedef EvaluationSrvRequest Request;
typedef EvaluationSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EvaluationSrv
} // namespace ramp_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ramp_msgs::EvaluationSrv > {
  static const char* value()
  {
    return "bb14ee9ba2b91774273c2644f7a15381";
  }

  static const char* value(const ::ramp_msgs::EvaluationSrv&) { return value(); }
};

template<>
struct DataType< ::ramp_msgs::EvaluationSrv > {
  static const char* value()
  {
    return "ramp_msgs/EvaluationSrv";
  }

  static const char* value(const ::ramp_msgs::EvaluationSrv&) { return value(); }
};


// service_traits::MD5Sum< ::ramp_msgs::EvaluationSrvRequest> should match 
// service_traits::MD5Sum< ::ramp_msgs::EvaluationSrv > 
template<>
struct MD5Sum< ::ramp_msgs::EvaluationSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ramp_msgs::EvaluationSrv >::value();
  }
  static const char* value(const ::ramp_msgs::EvaluationSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ramp_msgs::EvaluationSrvRequest> should match 
// service_traits::DataType< ::ramp_msgs::EvaluationSrv > 
template<>
struct DataType< ::ramp_msgs::EvaluationSrvRequest>
{
  static const char* value()
  {
    return DataType< ::ramp_msgs::EvaluationSrv >::value();
  }
  static const char* value(const ::ramp_msgs::EvaluationSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ramp_msgs::EvaluationSrvResponse> should match 
// service_traits::MD5Sum< ::ramp_msgs::EvaluationSrv > 
template<>
struct MD5Sum< ::ramp_msgs::EvaluationSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ramp_msgs::EvaluationSrv >::value();
  }
  static const char* value(const ::ramp_msgs::EvaluationSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ramp_msgs::EvaluationSrvResponse> should match 
// service_traits::DataType< ::ramp_msgs::EvaluationSrv > 
template<>
struct DataType< ::ramp_msgs::EvaluationSrvResponse>
{
  static const char* value()
  {
    return DataType< ::ramp_msgs::EvaluationSrv >::value();
  }
  static const char* value(const ::ramp_msgs::EvaluationSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RAMP_MSGS_MESSAGE_EVALUATIONSRV_H
