// Generated by gencpp from file ramp_msgs/EvaluationRequest.msg
// DO NOT EDIT!


#ifndef RAMP_MSGS_MESSAGE_EVALUATIONREQUEST_H
#define RAMP_MSGS_MESSAGE_EVALUATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ramp_msgs/RampTrajectory.h>
#include <ramp_msgs/RampTrajectory.h>
#include <ramp_msgs/CircleGroup.h>

namespace ramp_msgs
{
template <class ContainerAllocator>
struct EvaluationRequest_
{
  typedef EvaluationRequest_<ContainerAllocator> Type;

  EvaluationRequest_()
    : trajectory()
    , robot_radius(0.0)
    , currentTheta(0.0)
    , theta_cc(0.0)
    , obstacle_trjs()
    , obstacle_cir_groups()
    , imminent_collision(false)
    , offset(0.0)
    , full_eval(false)
    , consider_trans(false)
    , trans_possible(false)
    , hmap_eval(false)  {
    }
  EvaluationRequest_(const ContainerAllocator& _alloc)
    : trajectory(_alloc)
    , robot_radius(0.0)
    , currentTheta(0.0)
    , theta_cc(0.0)
    , obstacle_trjs(_alloc)
    , obstacle_cir_groups(_alloc)
    , imminent_collision(false)
    , offset(0.0)
    , full_eval(false)
    , consider_trans(false)
    , trans_possible(false)
    , hmap_eval(false)  {
  (void)_alloc;
    }



   typedef  ::ramp_msgs::RampTrajectory_<ContainerAllocator>  _trajectory_type;
  _trajectory_type trajectory;

   typedef double _robot_radius_type;
  _robot_radius_type robot_radius;

   typedef double _currentTheta_type;
  _currentTheta_type currentTheta;

   typedef double _theta_cc_type;
  _theta_cc_type theta_cc;

   typedef std::vector< ::ramp_msgs::RampTrajectory_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ramp_msgs::RampTrajectory_<ContainerAllocator> >::other >  _obstacle_trjs_type;
  _obstacle_trjs_type obstacle_trjs;

   typedef std::vector< ::ramp_msgs::CircleGroup_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ramp_msgs::CircleGroup_<ContainerAllocator> >::other >  _obstacle_cir_groups_type;
  _obstacle_cir_groups_type obstacle_cir_groups;

   typedef uint8_t _imminent_collision_type;
  _imminent_collision_type imminent_collision;

   typedef double _offset_type;
  _offset_type offset;

   typedef uint8_t _full_eval_type;
  _full_eval_type full_eval;

   typedef uint8_t _consider_trans_type;
  _consider_trans_type consider_trans;

   typedef uint8_t _trans_possible_type;
  _trans_possible_type trans_possible;

   typedef uint8_t _hmap_eval_type;
  _hmap_eval_type hmap_eval;





  typedef boost::shared_ptr< ::ramp_msgs::EvaluationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ramp_msgs::EvaluationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EvaluationRequest_

typedef ::ramp_msgs::EvaluationRequest_<std::allocator<void> > EvaluationRequest;

typedef boost::shared_ptr< ::ramp_msgs::EvaluationRequest > EvaluationRequestPtr;
typedef boost::shared_ptr< ::ramp_msgs::EvaluationRequest const> EvaluationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ramp_msgs::EvaluationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ramp_msgs::EvaluationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ramp_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ramp_msgs': ['/home/mason/Documents/evol_planner/src/packages/ramp_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ramp_msgs::EvaluationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ramp_msgs::EvaluationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ramp_msgs::EvaluationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ramp_msgs::EvaluationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ramp_msgs::EvaluationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ramp_msgs::EvaluationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ramp_msgs::EvaluationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "40e525bfb7e4a2a45b79429a4d3f00db";
  }

  static const char* value(const ::ramp_msgs::EvaluationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x40e525bfb7e4a2a4ULL;
  static const uint64_t static_value2 = 0x5b79429a4d3f00dbULL;
};

template<class ContainerAllocator>
struct DataType< ::ramp_msgs::EvaluationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ramp_msgs/EvaluationRequest";
  }

  static const char* value(const ::ramp_msgs::EvaluationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ramp_msgs::EvaluationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RampTrajectory trajectory\n\
float64 robot_radius\n\
float64 currentTheta\n\
float64 theta_cc\n\
RampTrajectory[] obstacle_trjs\n\
CircleGroup[] obstacle_cir_groups\n\
bool imminent_collision\n\
float64 offset\n\
bool full_eval\n\
\n\
bool consider_trans\n\
bool trans_possible\n\
bool hmap_eval\n\
\n\
================================================================================\n\
MSG: ramp_msgs/RampTrajectory\n\
Header header\n\
uint16 id\n\
trajectory_msgs/JointTrajectory trajectory\n\
uint16[] i_knotPoints\n\
ramp_msgs/BezierCurve[] curves\n\
ramp_msgs/Path holonomic_path\n\
\n\
bool feasible\n\
float64 fitness\n\
\n\
duration t_firstCollision\n\
int8 i_subPopulation\n\
\n\
duration t_start\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: trajectory_msgs/JointTrajectory\n\
Header header\n\
string[] joint_names\n\
JointTrajectoryPoint[] points\n\
================================================================================\n\
MSG: trajectory_msgs/JointTrajectoryPoint\n\
# Each trajectory point specifies either positions[, velocities[, accelerations]]\n\
# or positions[, effort] for the trajectory to be executed.\n\
# All specified values are in the same order as the joint names in JointTrajectory.msg\n\
\n\
float64[] positions\n\
float64[] velocities\n\
float64[] accelerations\n\
float64[] effort\n\
duration time_from_start\n\
\n\
================================================================================\n\
MSG: ramp_msgs/BezierCurve\n\
Header header\n\
\n\
ramp_msgs/MotionState[] points\n\
float64[] u_values\n\
\n\
ramp_msgs/MotionState[] segmentPoints\n\
ramp_msgs/MotionState[] controlPoints\n\
\n\
float64 l\n\
ramp_msgs/MotionState ms_maxVA\n\
ramp_msgs/MotionState ms_initialVA\n\
ramp_msgs/MotionState ms_begin\n\
float64 u_0\n\
float64 u_dot_0\n\
float64 u_dot_max\n\
float64 u_target\n\
\n\
================================================================================\n\
MSG: ramp_msgs/MotionState\n\
float64[] positions\n\
float64[] velocities\n\
float64[] accelerations\n\
float64[] jerks\n\
\n\
# change to duration\n\
float64 time\n\
\n\
================================================================================\n\
MSG: ramp_msgs/Path\n\
ramp_msgs/KnotPoint[] points\n\
\n\
================================================================================\n\
MSG: ramp_msgs/KnotPoint\n\
ramp_msgs/MotionState motionState\n\
uint32 stopTime\n\
\n\
================================================================================\n\
MSG: ramp_msgs/CircleGroup\n\
ramp_msgs/Circle fitCir\n\
ramp_msgs/Circle[] packedCirs\n\
\n\
================================================================================\n\
MSG: ramp_msgs/Circle\n\
geometry_msgs/Vector3 center\n\
float64 radius\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::ramp_msgs::EvaluationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ramp_msgs::EvaluationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.trajectory);
      stream.next(m.robot_radius);
      stream.next(m.currentTheta);
      stream.next(m.theta_cc);
      stream.next(m.obstacle_trjs);
      stream.next(m.obstacle_cir_groups);
      stream.next(m.imminent_collision);
      stream.next(m.offset);
      stream.next(m.full_eval);
      stream.next(m.consider_trans);
      stream.next(m.trans_possible);
      stream.next(m.hmap_eval);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EvaluationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ramp_msgs::EvaluationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ramp_msgs::EvaluationRequest_<ContainerAllocator>& v)
  {
    s << indent << "trajectory: ";
    s << std::endl;
    Printer< ::ramp_msgs::RampTrajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.trajectory);
    s << indent << "robot_radius: ";
    Printer<double>::stream(s, indent + "  ", v.robot_radius);
    s << indent << "currentTheta: ";
    Printer<double>::stream(s, indent + "  ", v.currentTheta);
    s << indent << "theta_cc: ";
    Printer<double>::stream(s, indent + "  ", v.theta_cc);
    s << indent << "obstacle_trjs[]" << std::endl;
    for (size_t i = 0; i < v.obstacle_trjs.size(); ++i)
    {
      s << indent << "  obstacle_trjs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ramp_msgs::RampTrajectory_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacle_trjs[i]);
    }
    s << indent << "obstacle_cir_groups[]" << std::endl;
    for (size_t i = 0; i < v.obstacle_cir_groups.size(); ++i)
    {
      s << indent << "  obstacle_cir_groups[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ramp_msgs::CircleGroup_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacle_cir_groups[i]);
    }
    s << indent << "imminent_collision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.imminent_collision);
    s << indent << "offset: ";
    Printer<double>::stream(s, indent + "  ", v.offset);
    s << indent << "full_eval: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.full_eval);
    s << indent << "consider_trans: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.consider_trans);
    s << indent << "trans_possible: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trans_possible);
    s << indent << "hmap_eval: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hmap_eval);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAMP_MSGS_MESSAGE_EVALUATIONREQUEST_H
