// Generated by gencpp from file ramp_msgs/ModificationRequest.msg
// DO NOT EDIT!


#ifndef RAMP_MSGS_MESSAGE_MODIFICATIONREQUEST_H
#define RAMP_MSGS_MESSAGE_MODIFICATIONREQUEST_H

#include <ros/service_traits.h>


#include <ramp_msgs/ModificationRequestRequest.h>
#include <ramp_msgs/ModificationRequestResponse.h>


namespace ramp_msgs
{

struct ModificationRequest
{

typedef ModificationRequestRequest Request;
typedef ModificationRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ModificationRequest
} // namespace ramp_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ramp_msgs::ModificationRequest > {
  static const char* value()
  {
    return "e2f4c66b0fd63d5e71b5be50fa7c661e";
  }

  static const char* value(const ::ramp_msgs::ModificationRequest&) { return value(); }
};

template<>
struct DataType< ::ramp_msgs::ModificationRequest > {
  static const char* value()
  {
    return "ramp_msgs/ModificationRequest";
  }

  static const char* value(const ::ramp_msgs::ModificationRequest&) { return value(); }
};


// service_traits::MD5Sum< ::ramp_msgs::ModificationRequestRequest> should match 
// service_traits::MD5Sum< ::ramp_msgs::ModificationRequest > 
template<>
struct MD5Sum< ::ramp_msgs::ModificationRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ramp_msgs::ModificationRequest >::value();
  }
  static const char* value(const ::ramp_msgs::ModificationRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ramp_msgs::ModificationRequestRequest> should match 
// service_traits::DataType< ::ramp_msgs::ModificationRequest > 
template<>
struct DataType< ::ramp_msgs::ModificationRequestRequest>
{
  static const char* value()
  {
    return DataType< ::ramp_msgs::ModificationRequest >::value();
  }
  static const char* value(const ::ramp_msgs::ModificationRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ramp_msgs::ModificationRequestResponse> should match 
// service_traits::MD5Sum< ::ramp_msgs::ModificationRequest > 
template<>
struct MD5Sum< ::ramp_msgs::ModificationRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ramp_msgs::ModificationRequest >::value();
  }
  static const char* value(const ::ramp_msgs::ModificationRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ramp_msgs::ModificationRequestResponse> should match 
// service_traits::DataType< ::ramp_msgs::ModificationRequest > 
template<>
struct DataType< ::ramp_msgs::ModificationRequestResponse>
{
  static const char* value()
  {
    return DataType< ::ramp_msgs::ModificationRequest >::value();
  }
  static const char* value(const ::ramp_msgs::ModificationRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RAMP_MSGS_MESSAGE_MODIFICATIONREQUEST_H
