// Generated by gencpp from file ramp_msgs/NavModificationRequest.msg
// DO NOT EDIT!


#ifndef RAMP_MSGS_MESSAGE_NAVMODIFICATIONREQUEST_H
#define RAMP_MSGS_MESSAGE_NAVMODIFICATIONREQUEST_H

#include <ros/service_traits.h>


#include <ramp_msgs/NavModificationRequestRequest.h>
#include <ramp_msgs/NavModificationRequestResponse.h>


namespace ramp_msgs
{

struct NavModificationRequest
{

typedef NavModificationRequestRequest Request;
typedef NavModificationRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NavModificationRequest
} // namespace ramp_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ramp_msgs::NavModificationRequest > {
  static const char* value()
  {
    return "3811dc7a15f462d593d653ffa9b613c5";
  }

  static const char* value(const ::ramp_msgs::NavModificationRequest&) { return value(); }
};

template<>
struct DataType< ::ramp_msgs::NavModificationRequest > {
  static const char* value()
  {
    return "ramp_msgs/NavModificationRequest";
  }

  static const char* value(const ::ramp_msgs::NavModificationRequest&) { return value(); }
};


// service_traits::MD5Sum< ::ramp_msgs::NavModificationRequestRequest> should match 
// service_traits::MD5Sum< ::ramp_msgs::NavModificationRequest > 
template<>
struct MD5Sum< ::ramp_msgs::NavModificationRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ramp_msgs::NavModificationRequest >::value();
  }
  static const char* value(const ::ramp_msgs::NavModificationRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ramp_msgs::NavModificationRequestRequest> should match 
// service_traits::DataType< ::ramp_msgs::NavModificationRequest > 
template<>
struct DataType< ::ramp_msgs::NavModificationRequestRequest>
{
  static const char* value()
  {
    return DataType< ::ramp_msgs::NavModificationRequest >::value();
  }
  static const char* value(const ::ramp_msgs::NavModificationRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ramp_msgs::NavModificationRequestResponse> should match 
// service_traits::MD5Sum< ::ramp_msgs::NavModificationRequest > 
template<>
struct MD5Sum< ::ramp_msgs::NavModificationRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ramp_msgs::NavModificationRequest >::value();
  }
  static const char* value(const ::ramp_msgs::NavModificationRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ramp_msgs::NavModificationRequestResponse> should match 
// service_traits::DataType< ::ramp_msgs::NavModificationRequest > 
template<>
struct DataType< ::ramp_msgs::NavModificationRequestResponse>
{
  static const char* value()
  {
    return DataType< ::ramp_msgs::NavModificationRequest >::value();
  }
  static const char* value(const ::ramp_msgs::NavModificationRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RAMP_MSGS_MESSAGE_NAVMODIFICATIONREQUEST_H
