// Generated by gencpp from file ramp_msgs/NavModificationRequestRequest.msg
// DO NOT EDIT!


#ifndef RAMP_MSGS_MESSAGE_NAVMODIFICATIONREQUESTREQUEST_H
#define RAMP_MSGS_MESSAGE_NAVMODIFICATIONREQUESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Path.h>

namespace ramp_msgs
{
template <class ContainerAllocator>
struct NavModificationRequestRequest_
{
  typedef NavModificationRequestRequest_<ContainerAllocator> Type;

  NavModificationRequestRequest_()
    : paths()
    , op()
    , repair_dist(0.0)
    , repair_dir(0.0)
    , repair_ob_r(0.0)  {
    }
  NavModificationRequestRequest_(const ContainerAllocator& _alloc)
    : paths(_alloc)
    , op(_alloc)
    , repair_dist(0.0)
    , repair_dir(0.0)
    , repair_ob_r(0.0)  {
  (void)_alloc;
    }



   typedef std::vector< ::nav_msgs::Path_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::nav_msgs::Path_<ContainerAllocator> >::other >  _paths_type;
  _paths_type paths;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _op_type;
  _op_type op;

   typedef double _repair_dist_type;
  _repair_dist_type repair_dist;

   typedef double _repair_dir_type;
  _repair_dir_type repair_dir;

   typedef double _repair_ob_r_type;
  _repair_ob_r_type repair_ob_r;





  typedef boost::shared_ptr< ::ramp_msgs::NavModificationRequestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ramp_msgs::NavModificationRequestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NavModificationRequestRequest_

typedef ::ramp_msgs::NavModificationRequestRequest_<std::allocator<void> > NavModificationRequestRequest;

typedef boost::shared_ptr< ::ramp_msgs::NavModificationRequestRequest > NavModificationRequestRequestPtr;
typedef boost::shared_ptr< ::ramp_msgs::NavModificationRequestRequest const> NavModificationRequestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ramp_msgs::NavModificationRequestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ramp_msgs::NavModificationRequestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ramp_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ramp_msgs': ['/home/mason/Documents/evol_planner/src/packages/ramp_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ramp_msgs::NavModificationRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ramp_msgs::NavModificationRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ramp_msgs::NavModificationRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ramp_msgs::NavModificationRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ramp_msgs::NavModificationRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ramp_msgs::NavModificationRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ramp_msgs::NavModificationRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6b0c9277cbfc20c7bb397f2349b399a";
  }

  static const char* value(const ::ramp_msgs::NavModificationRequestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6b0c9277cbfc20cULL;
  static const uint64_t static_value2 = 0x7bb397f2349b399aULL;
};

template<class ContainerAllocator>
struct DataType< ::ramp_msgs::NavModificationRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ramp_msgs/NavModificationRequestRequest";
  }

  static const char* value(const ::ramp_msgs::NavModificationRequestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ramp_msgs::NavModificationRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_msgs/Path[] paths\n\
string op\n\
float64 repair_dist\n\
float64 repair_dir\n\
float64 repair_ob_r\n\
\n\
\n\
================================================================================\n\
MSG: nav_msgs/Path\n\
#An array of poses that represents a Path for a robot to follow\n\
Header header\n\
geometry_msgs/PoseStamped[] poses\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::ramp_msgs::NavModificationRequestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ramp_msgs::NavModificationRequestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.paths);
      stream.next(m.op);
      stream.next(m.repair_dist);
      stream.next(m.repair_dir);
      stream.next(m.repair_ob_r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavModificationRequestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ramp_msgs::NavModificationRequestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ramp_msgs::NavModificationRequestRequest_<ContainerAllocator>& v)
  {
    s << indent << "paths[]" << std::endl;
    for (size_t i = 0; i < v.paths.size(); ++i)
    {
      s << indent << "  paths[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nav_msgs::Path_<ContainerAllocator> >::stream(s, indent + "    ", v.paths[i]);
    }
    s << indent << "op: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.op);
    s << indent << "repair_dist: ";
    Printer<double>::stream(s, indent + "  ", v.repair_dist);
    s << indent << "repair_dir: ";
    Printer<double>::stream(s, indent + "  ", v.repair_dir);
    s << indent << "repair_ob_r: ";
    Printer<double>::stream(s, indent + "  ", v.repair_ob_r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAMP_MSGS_MESSAGE_NAVMODIFICATIONREQUESTREQUEST_H
