// Generated by gencpp from file ramp_msgs/RampTrajectory.msg
// DO NOT EDIT!


#ifndef RAMP_MSGS_MESSAGE_RAMPTRAJECTORY_H
#define RAMP_MSGS_MESSAGE_RAMPTRAJECTORY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <trajectory_msgs/JointTrajectory.h>
#include <ramp_msgs/BezierCurve.h>
#include <ramp_msgs/Path.h>

namespace ramp_msgs
{
template <class ContainerAllocator>
struct RampTrajectory_
{
  typedef RampTrajectory_<ContainerAllocator> Type;

  RampTrajectory_()
    : header()
    , id(0)
    , trajectory()
    , i_knotPoints()
    , curves()
    , holonomic_path()
    , feasible(false)
    , fitness(0.0)
    , t_firstCollision()
    , i_subPopulation(0)
    , t_start()  {
    }
  RampTrajectory_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , trajectory(_alloc)
    , i_knotPoints(_alloc)
    , curves(_alloc)
    , holonomic_path(_alloc)
    , feasible(false)
    , fitness(0.0)
    , t_firstCollision()
    , i_subPopulation(0)
    , t_start()  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _id_type;
  _id_type id;

   typedef  ::trajectory_msgs::JointTrajectory_<ContainerAllocator>  _trajectory_type;
  _trajectory_type trajectory;

   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _i_knotPoints_type;
  _i_knotPoints_type i_knotPoints;

   typedef std::vector< ::ramp_msgs::BezierCurve_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ramp_msgs::BezierCurve_<ContainerAllocator> >::other >  _curves_type;
  _curves_type curves;

   typedef  ::ramp_msgs::Path_<ContainerAllocator>  _holonomic_path_type;
  _holonomic_path_type holonomic_path;

   typedef uint8_t _feasible_type;
  _feasible_type feasible;

   typedef double _fitness_type;
  _fitness_type fitness;

   typedef ros::Duration _t_firstCollision_type;
  _t_firstCollision_type t_firstCollision;

   typedef int8_t _i_subPopulation_type;
  _i_subPopulation_type i_subPopulation;

   typedef ros::Duration _t_start_type;
  _t_start_type t_start;





  typedef boost::shared_ptr< ::ramp_msgs::RampTrajectory_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ramp_msgs::RampTrajectory_<ContainerAllocator> const> ConstPtr;

}; // struct RampTrajectory_

typedef ::ramp_msgs::RampTrajectory_<std::allocator<void> > RampTrajectory;

typedef boost::shared_ptr< ::ramp_msgs::RampTrajectory > RampTrajectoryPtr;
typedef boost::shared_ptr< ::ramp_msgs::RampTrajectory const> RampTrajectoryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ramp_msgs::RampTrajectory_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ramp_msgs::RampTrajectory_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ramp_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ramp_msgs': ['/home/mason/Documents/evol_planner/src/packages/ramp_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ramp_msgs::RampTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ramp_msgs::RampTrajectory_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ramp_msgs::RampTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ramp_msgs::RampTrajectory_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ramp_msgs::RampTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ramp_msgs::RampTrajectory_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ramp_msgs::RampTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13d45cd502292765a8d2b315f6b3795c";
  }

  static const char* value(const ::ramp_msgs::RampTrajectory_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13d45cd502292765ULL;
  static const uint64_t static_value2 = 0xa8d2b315f6b3795cULL;
};

template<class ContainerAllocator>
struct DataType< ::ramp_msgs::RampTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ramp_msgs/RampTrajectory";
  }

  static const char* value(const ::ramp_msgs::RampTrajectory_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ramp_msgs::RampTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint16 id\n\
trajectory_msgs/JointTrajectory trajectory\n\
uint16[] i_knotPoints\n\
ramp_msgs/BezierCurve[] curves\n\
ramp_msgs/Path holonomic_path\n\
\n\
bool feasible\n\
float64 fitness\n\
\n\
duration t_firstCollision\n\
int8 i_subPopulation\n\
\n\
duration t_start\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: trajectory_msgs/JointTrajectory\n\
Header header\n\
string[] joint_names\n\
JointTrajectoryPoint[] points\n\
================================================================================\n\
MSG: trajectory_msgs/JointTrajectoryPoint\n\
# Each trajectory point specifies either positions[, velocities[, accelerations]]\n\
# or positions[, effort] for the trajectory to be executed.\n\
# All specified values are in the same order as the joint names in JointTrajectory.msg\n\
\n\
float64[] positions\n\
float64[] velocities\n\
float64[] accelerations\n\
float64[] effort\n\
duration time_from_start\n\
\n\
================================================================================\n\
MSG: ramp_msgs/BezierCurve\n\
Header header\n\
\n\
ramp_msgs/MotionState[] points\n\
float64[] u_values\n\
\n\
ramp_msgs/MotionState[] segmentPoints\n\
ramp_msgs/MotionState[] controlPoints\n\
\n\
float64 l\n\
ramp_msgs/MotionState ms_maxVA\n\
ramp_msgs/MotionState ms_initialVA\n\
ramp_msgs/MotionState ms_begin\n\
float64 u_0\n\
float64 u_dot_0\n\
float64 u_dot_max\n\
float64 u_target\n\
\n\
================================================================================\n\
MSG: ramp_msgs/MotionState\n\
float64[] positions\n\
float64[] velocities\n\
float64[] accelerations\n\
float64[] jerks\n\
\n\
# change to duration\n\
float64 time\n\
\n\
================================================================================\n\
MSG: ramp_msgs/Path\n\
ramp_msgs/KnotPoint[] points\n\
\n\
================================================================================\n\
MSG: ramp_msgs/KnotPoint\n\
ramp_msgs/MotionState motionState\n\
uint32 stopTime\n\
";
  }

  static const char* value(const ::ramp_msgs::RampTrajectory_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ramp_msgs::RampTrajectory_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.trajectory);
      stream.next(m.i_knotPoints);
      stream.next(m.curves);
      stream.next(m.holonomic_path);
      stream.next(m.feasible);
      stream.next(m.fitness);
      stream.next(m.t_firstCollision);
      stream.next(m.i_subPopulation);
      stream.next(m.t_start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RampTrajectory_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ramp_msgs::RampTrajectory_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ramp_msgs::RampTrajectory_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.id);
    s << indent << "trajectory: ";
    s << std::endl;
    Printer< ::trajectory_msgs::JointTrajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.trajectory);
    s << indent << "i_knotPoints[]" << std::endl;
    for (size_t i = 0; i < v.i_knotPoints.size(); ++i)
    {
      s << indent << "  i_knotPoints[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.i_knotPoints[i]);
    }
    s << indent << "curves[]" << std::endl;
    for (size_t i = 0; i < v.curves.size(); ++i)
    {
      s << indent << "  curves[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ramp_msgs::BezierCurve_<ContainerAllocator> >::stream(s, indent + "    ", v.curves[i]);
    }
    s << indent << "holonomic_path: ";
    s << std::endl;
    Printer< ::ramp_msgs::Path_<ContainerAllocator> >::stream(s, indent + "  ", v.holonomic_path);
    s << indent << "feasible: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.feasible);
    s << indent << "fitness: ";
    Printer<double>::stream(s, indent + "  ", v.fitness);
    s << indent << "t_firstCollision: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.t_firstCollision);
    s << indent << "i_subPopulation: ";
    Printer<int8_t>::stream(s, indent + "  ", v.i_subPopulation);
    s << indent << "t_start: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.t_start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAMP_MSGS_MESSAGE_RAMPTRAJECTORY_H
